### ISSUE TITLE
Lookup: revoked uid marked as non revoked

### ISSUE THREAD

**Issue by mmpio** [duniter/duniter#388]
See http://testnet.duniter.inso.ovh/wot/lookup/smoul

    ...
    {
      "pubkey": "2sq8bBDQGK74f1eD3mAPQVgHCmFdijZr9nbv16FwbokX",
      "uids": [
        {
          "uid": "smoul",
          "meta": {
            "timestamp": "16866-000AFA83CDBEC9BC83555DE0C8796F43CBF1C4AAE309C8A6D02D78C73F488983"
          },
          "revoked": false,
          "revocation_sig": "o+23Mz4wB59NnSOUPQK0RsDW60N/rQYF3KY7qRcdY/vssGTORI1HL8CM14AZ+70cS4LOmV0a6nj9f+ETV97ZDQ==",
          "self": "/2s9Qmn/z5wzL1QQzii4eALbFuTMbWMLBvtwe2NdWcQ5GH9lHJAbh0QSafrHTVjppzdpUNoyyZ5fIcVDwps4Bw==",
          "others": []
        }
      ],
      "signed": []
    },
    ...

**Comment by c-geek** [comment]
After digging this issue, it appears there is not bug at all: the `revoked` field should be true *only if the revocation has been written in the blockchain*, which is not the case here. This explains why we have this `revoked` field along with a `revocation_sig` field, since a revocation signature already means we tried to revoke the identity.

The `revoked` field means *revocation has been written*.

However, I indeed had a bug in the specific scenario where a revocation document is received but the inner identity is not known yet. In such case Duniter creates the identity in the database, but was valuing `revoked` to `true`, contrary to the rule I detailed above. So I fixed this and added a Unit Test to cover this scenario.

You can have a look at [these tests](https://github.com/duniter/duniter/blob/dev/test/integration/revocation-test.js#L97-L130) covering the 3 possible expectations: *normal* identity, *revoking* identity and *revoked*.
