### ISSUE TITLE
salt - entropy don't match the good user concept.

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#439]
Je peux parler d'"entropie" pour spécifier la manière dont l'algorithme fonctionne, c'est général, mais ça ne spécifie pas l'entropie personnelle choisie par l'utilisateur au final. Tout comme "variable" ne dit pas la valeur spécifique 10 ou 25 que l'on met dedans.

I propose so to use : "secret key" = "clé secrète", and inform the end user that he has two password levels to connect to its account, he can keep in separated points : 

- secret key
- password

And use those concepts in all clients will help to understand what it is about : some secret own passwords able to connect to its account to manage it.

**Comment by c-geek** [comment]
We could do what you propose, but most importantly we have to be *very clear* that the combination *has to be the most possibly unique and hard to guess* so that the password + secret are secure.

Also we missed a point: these 2 words are not enough, they have to be interpreted under [Nrp values](https://en.wikipedia.org/wiki/Scrypt#Algorithm), which in Sakia/Cesium are just not mentionned but the values are: [`N = 4096, r  = 16, p = 1`](https://github.com/duniter/duniter/blob/master/app/lib/crypto.js#L14-L18).

**Comment by c-geek** [comment]
Note: Sakia already have issue duniter/sakia#197 for that purpose.

**Comment by c-geek** [comment]
Fixed by https://github.com/duniter/duniter-ui/commit/084b5dc344e57a673c1f1dd9bd8e5384365b9386.

**Comment by Insoleet** [comment]
Perfect, now that two of the main UIs are using the "secret key" word, Sakia just have to follow :+1:
