### ISSUE TITLE
Wrong timestamp on transaction

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#470]
Reported by @fluidlog.
![bad timestamp cesium](https://cloud.githubusercontent.com/assets/6891994/15783529/d0b54cae-29ae-11e6-83cd-2cabbe99add8.png)
A "last transaction" 2 hour ago appear with 2H+12H = 14 hours ago.
It seems there is 12h of offset when record a transaction.
For example, In real life, Galuel has give me money at 15h (approximatively)

--------------

Wrong timestamp on transaction from Galuel to fluidlog which have been done 3 Juin at 15h:
```json
curl node:port/tx/history/8PMaLKJNaCcdWPeHs6xdRhuuvBQLeCGBAagQPuxoga63
      {
        "version": 2,
        "issuers": [
          "5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6"
        ],
        "inputs": [
          "T:06138AF5F430FE965ADBAF6E8C6041AC56DDFE9766CF6D4C3C09E918AE9658E3:1"
        ],
        "outputs": [
          "500:0:SIG(8PMaLKJNaCcdWPeHs6xdRhuuvBQLeCGBAagQPuxoga63)",
          "66387:0:SIG(5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6)"
        ],
        "comment": "fggggfd",
        "locktime": "0",
        "signatures": [
          "SfRsG/yD6V2pONtNG4/wmWoW0F1bja3YIjLBR9AXEdqJ3hM35JYvwljSHD6k3AyLtXmBzF8sgl/o/Fq4b/K5Bw=="
        ],
        "hash": "E0D3BEAEE417B9CBBF9EFB7D5655A96888BAAFDF5D113945779FA11132D6B19A",
        "block_number": 11120,
        "time": 1464915733,
        "received": 0
      }
```

This timestamp correspond to `ven. juin  3 03:02:13 CEST 2016`.

**Comment by c-geek** [comment]
The time given here is *blockchain write time*. During RML7 we had the blockchain stuck during the night, leading to an offset in current time (= the blockchain was late).

That's why this transaction has such a time. Also this explains why the time of this transaction is `1464915733` (=  3/6/2016 3:02:13) so written in the "night": this is the time at which the blockchain was stuck. So as soon as we restarted it, the transaction has been written.

See http://duniter.org:8999/blockchain/block/11120
