### ISSUE TITLE
/wot/requirements return error "written.json is not a function"

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#478]
http://cgeek.fr:9330/wot/requirements/CGJNtdxLishCkyhW4knEvZu4wRiXAJjU8pVfzAMEcBUc

{
ucode: 1002,
message: "written.json is not a function"
}

**Comment by c-geek** [comment]
OK the real underneath error was:

```js
{
  ucode: 1002,
  message: "Too old identity"
}
```

But a bug in the code was putting an incorrect error message instead of "Too old identity". This will be fixed in next release.

**Comment by c-geek** [comment]
I've added a new field named `expired` which tells if the identity is considered expired (that is: if the identity has not been written yet and, given the time which passed, the identity will never be written ever).

Here is an example of the new result:

```js
{
  "identities": [
    {
      "pubkey": "CGJNtdxLishCkyhW4knEvZu4wRiXAJjU8pVfzAMEcBUc",
      "uid": "dig",
      "meta": {
        "timestamp": "10973-00002FA3A6DB2D3A64B31F7533193803D2BB5F63E13672DA6ADB03B1587CD9BB"
      },
      "expired": true,
      "outdistanced": false,
      "certifications": [],
      "membershipPendingExpiresIn": 0,
      "membershipExpiresIn": 0
    },
    {
      "pubkey": "CGJNtdxLishCkyhW4knEvZu4wRiXAJjU8pVfzAMEcBUc",
      "uid": "dig",
      "meta": {
        "timestamp": "10978-000023DFE33C617A96A44DB32763C29EF0203FCE97D62ADC72A1BC8F1B6F75DC"
      },
      "expired": true,
      "outdistanced": false,
      "certifications": [],
      "membershipPendingExpiresIn": 0,
      "membershipExpiresIn": 0
    }
  ]
}
```

Note how `outdistanced`, `certifications`, `membershipPendingExpiresIn`, `membershipExpiresIn` has a default value: since the identity is expired, I do not take the resources to compute these data. So you should definitely **not interprete them** if `expired = true`.
