### ISSUE TITLE
Open Cesium in a new tab

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#517]
With YunoHost package.
Logs are open in a new tab.
Could Cesium be opened in a new tab? Currently, it open a new window.
I think it will still open a new window for node-webkit.

**Comment by M5oul** [comment]
I reverted [this line](https://github.com/duniter/duniter-ui/commit/5e262725d59fb1d8645790f55cacc1fded611c54#diff-6a4090af14da49b876e3a7dc67942532L35) and it still opening in a new window :(

**Comment by c-geek** [comment]
Yes, because:

* `openWindow` is when we want to open Window, always (web or desktop)
* `openExternal` is when we want to open a browser, always (web or desktop)

But we have no function to open a new Window in desktop, and fallback to new tab in a web browser. The "logs" link is a bit special and does not call one or the other of these functions.

I've to make a gnu one :)
