### ISSUE TITLE
Limit identities creation

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#568]
I started to translate [Sybil attack Wikipedia article](https://fr.wikipedia.org/wiki/Attaque_Sybil#Description) from English to french.

Which says:
>  A reputation system's vulnerability to a Sybil attack depends on how cheaply identities can be generated

I think it's an awesome tool to lock Sybil attack.

---

For that, we could increase the cost of creating an new identity.
Currently, the cost is almost null, by a simple click.

To increase the cost, we could:
- ask for a minimal certification: one certification to create a new identity
- use two level of certification:
 - high level for members certifications
 - low level for identity certifications (with a maximum quantity)
 - seems annoying to implement

---

Problems of that new feature:
- anonymous account won't be easy to create without a trust link. We will see that later.
- many users account
- other accounts of same person.

---

To summarize, I don't think we should be able to create infinity quantity of identities.
It's kind of dangerous.
We should be able to create non-member account because it's useful.
For that, a member we must be able to create a limited quantity of identities, we could say for instance 20.

---
People who don't have a member account will have to ask to a member to give a certification to this identity to make works. It's a small trust link.

---
We could have a problem if that person ask many certification for this non-member identity which could reach necessary number of certification to become member.
Solutions: 
- this identity could receive at max one certification.
- use member and non-member certifications level.

**Comment by modulix** [comment]
If i understand what you mean, there will be 3 steps ?
* Create account (new pubkey)
* Ask for certification of identity (new uid), should be done by one of members or non member with uid
* Ask for X certifications to become member (member flag), should be done by X other members

**Comment by M5oul** [comment]
Yep, I think you understand what I mean.

I mean that an identity couldn't be easily created like today.
To create a new identity we need a member identity to certify it.
In other words, everyone could create a new identity, but to become a valid identity (which could receive and send money), this identity must receive at least Y certifications from members identities. For instance, one certification seems good enough.

Finally, I really like the idea.

**Comment by c-geek** [comment]
Actually, maybe you talk about 2 things here:

* identity spam in sandboxes
* identity spam in the WoT

Spamming the WoT is not possible, since it requires certifications of members which cannot be done instantly, their is a delay between each certification (`sigDelay`) which limits a lot the spam.

Spamming the [sandboxes](https://github.com/duniter/duniter/issues/374#issuecomment-203642194) is no more possible since duniter@0.22.0, because the sandboxes now have a size and protections.

More precisely, when you say:

> ask for a minimal certification: one certification to create a new identity

This is a sandbox criteria, so once the sandbox of identities is full for a given node (let's say, 20 identities sized sandbox) then the node refuses any new identity that cannot override an identity of the sandbox.

For example, imagine sandbox of identities S(I, 20):

    I1 - 0 certs
    I2 - 0 certs
    I3 - 0 certs
    ...
    I20 - 0 certs

Then if a new identity `I21 - 0 certs` comes in, it will be rejected by the node. But if a new `I22 - 1 certs` comes in, it will override some other identity - let's say `I1 - 0 certs` because it has more chances to become a real identity in the WoT (it has more certs !).

**Comment by c-geek** [comment]
So, I think this issue is unfounded. I close it.
