### ISSUE TITLE
Proposition for better difficulty PoW computation

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#569]
I propose a better way to compute Proof of Work difficulty to have numbers more explicit and which represents in a more realistic way how strong machines are working on it.

### Definitions
- `H`: hexadecimal possibilities, each char can have 16 values: `[0-9A-F]`.
- `P`: valid possibilities
- `pos`: position on the string

### Current computing difficulty
[Proof of Work protocol documentation](https://github.com/duniter/duniter/blob/master/doc/Protocol.md#proof-of-work-1) on how difficulty is currently computed.
Currently difficulty is calculated with a sum of difficulties of each char to appear:

> Difficulty = Σ (pos = 0 ; pos += 1 ; max(len)) [H - P(pos) + 1]
Difficulty = [H - P(pos(0)) + 1] + [H - P(pos(1)) + 1] + [H - P(pos(n)) + 1] + [H - P(pos(n+1)) + 1]…

For instance: to match `0000*`, difficulty = 16 × 4 = 64.

### Compute difficulty proposition
Computation must be done with multiplication to fit with probabilities rules:

> Difficulty = Π (pos = 0 ; pos += 1 ; max(len)) [H - P(pos) + 1]
Difficulty = [H - P(pos(0)) + 1] × [H - P(pos(1)) + 1] × [H - P(pos(n)) + 1] × [H - P(pos(n+1)) + 1]…

For instance: to match `0000*`, difficulty = 16⁴ = 65.563.

#### Probability
With this difficulty computing, we could also compute probability to found a valid block at each test:
> Probability = 1 / Difficulty

### Results comparison table

| Match | Σ Difficulty | Π Difficulty | Probability |
| :--: | :--: | :--: | :--: |
| `*****` = `[0-9A-F]****` | 1 | 1 | 1/1 |
| `[0-9]****` | 7 | (16 - 10 + 1) = 7 | 1/(16 - 10 + 1) = 1/7 |
| `[0-1]****` | 15 | (16 - 2 + 1) = 15 | 1/(16 - 2 + 1) = 1/15 |
| `0****` | 16 | 16 | 1/[16 - 1 + 1] = 1/16 |
| `0[0-9]***` | 16 + (16 - 10 + 1) = 24 | 16 × (16 - 10 + 1) = 112 | 1/112 |
| `00***` | 16 × 2 = 32 | 16² = 256 | 1/16² |
| `0000*` | 16 × 4 = 64 | 16⁴ = 65.563 | 1/16⁴ |
| `0000[0-5]` | 16 × 4 + 6 = 70 | 16⁴ × (16 - 10) = 393.216 | 1/[16⁴ × (16 - 10)] |

As you could see 70 is very different than 393k.

### Implementation
I don't know what do that means for implementation.
May be, only changing calculation formula?
Does it impact PoW computation?

**Comment by c-geek** [comment]
OK this is embarrassing because in the process of writing the answer, I noticed the flaw in the protocol. Anyway, I will answer you and explain what is wrong and how to fix it (it's easy).

-----

Actually, I think there is nothing to change.

We could make an anology with Libre Currency:

* Σ Difficulty is like quantitative view
* Π Difficulty is like relative view
* Probability is another view, based on Π Difficulty view

Because when quantitative says 32, the real difficulty is not 32 times harder than difficulty 0, but `(√(√2))^(32) = 256` times the difficulty 0. This is your Π Difficulty.

So Π Difficulty is just the relative view of Σ Difficulty.

----

Now, what is wrong in the protocol is that I do not use √(√2) `= 1.18` to evaluate the toughness of block generation, but for some reason I used √(16/15) `= 1.066`.

So the protocol considers a block should be generated between an interval of `[ currentDifficulty / 1,066 ; currentDifficulty * 1,066 ]` which of course, given the real, physical ratio of hexadecimal difficulty, should be `[ currentDifficulty / 1,189 ; currentDifficulty * 1,189 ]` which is a wider range of possible times to compute the block without needing to change the difficulty.

Consequences? When using `[ average / 1,066 ; average * 1,066 ]` formula, statistically the block generation time is either under or above this average, *but rarely within* the intervalt. So we had a unstable difficulty.

So thanks for your questionning, it explains why I had an unstable difficulty despite I had only one node!

So what will change in the protocol is: replace `1,066` by `1,189`.

**Comment by c-geek** [comment]
So I close the issue, your question raised a problem which has to be fixed.

**Comment by c-geek** [comment]
Stability is rather good now, even on high frequency blockchain (average block generation = 20 seconds):

![image](https://cloud.githubusercontent.com/assets/969136/18065262/7ed6a576-6e33-11e6-95ee-91add8964945.png)

**Comment by M5oul** [comment]
I am very glad it permits to fix this Proof-of-Work computation problem by understanding my proposition.
That's pretty cool PoW works better with one node.

---

But, I am not very agree with:
> - Σ Difficulty is like quantitative view
- Π Difficulty is like relative view

because I don't think difficulty can be viewed in different referential.

I really think Duniter must use Π difficulty computation.

I could be wrong as I didn't study and understand how difficulty/PoW exactly works as I didn't understand formulas used which are different than mines.

It's not a priority at all and could be done after first libre currency launched.
But, I think it's a better way for newcomers in Duniter world to understand PoW with a better difficulty computation.

Furthermore, you were also put into error with Σ difficulty computation.
It's more elegant to use Π difficulty computation.

That's mathematically wrong, as you can't do probabilities with Σ difficulties.

Did you take this formula from other crypto-currencies/bitcoin?
I found nothing interesting or something I can understand about how are calculated bitcoin difficulty.

- [I found that](https://bitcoin.stackexchange.com/questions/23099/what-does-the-mining-difficulty-number-really-mean/35807#35807)

**Comment by c-geek** [comment]
Formulas in the protocol are exactly the same as yours, it is just said with different words.

> Furthermore, you were also put into error with Σ difficulty computation.

Actually, it is the opposite: I wrongly understood Π difficulty. I concluded, for some weird reason, that `16 = (√(16/15))^16`, which of course is wrong, the good formula is `16 = (√√2)^16`

But in the end there is absolutely nothing to change, the PoW mechanism uses both Σ & Π difficulties, it is just that Σ is used for knowing the scale step, while Π is the physical difficulty *implied by* Σ difficulty.

Let's define: 

* `Σdiff` is the Σ difficulty
* `Πdiff` is the Π difficulty

What I'm saying is that you have `Πdiff = Π(Σdiff) = (√(√2))^Σdiff`. You also have `Probability(Πdiff) = 1/Πdiff = Probability((√(√2))^Σdiff) = 1/((√(√2))^Σdiff)` if you want to make probabilities.

So Σdiff is already working, we don't need any changes. What you need however are Π(Σdiff) glasses, or Probability(Π(Σdiff)) if you want to make probabilities, because Duniter expresses with Σdiff, and you want to see with Πdiff or Probability(Πdiff).

So everything is OK.

**Comment by M5oul** [comment]
Let's say `(√(√2))^Σdiff = 2^(Σdiff/4)` which I found more explicit.

I will demonstrate that `Πdiff(Σdiff) = (√(√2))^Σdiff` formula is not the same as my formula for all matches:

> Πdiff = Π (pos = 0 ; pos += 1 ; max(len)) [H - P(pos) + 1]
> Πdiff = [H - P(pos(0)) + 1] × [H - P(pos(1)) + 1] × [H - P(pos(n)) + 1] × [H - P(pos(n+1)) + 1]…`.

#### Table
| match         | Σdiff | `Πdiff(Σdiff) = 2^(Σdiff/4)` | `Πdiff(upper formula)` |
|:--:               |:--:     |:--:                                               |:--:                     |
| `0****`         | 16    | 2^(16/4) = 2⁴ = 16                      | 16                    |
| `0000*`       | 64    | 2^(64/4) = 2¹⁶ = 65.536              | 65.536             |
|                    |         |                                                   |                         |
| `[0-1]****`    | 15    | 2^(15/4) = 13,45 ≠ 15                 | 15                    |
| `0000[0-5]` | 70     | 2^(70/4) = 185.363,8 ≠ 393.216 | 393.216           |

#### Words
- `Πdiff(Σdiff) = 2^(Σdiff/4)` works for some values like:
 - `Πdiff(16) = 2^(16/4) = 2⁴ = 16` to match `0****`.
 - `Πdiff(64) = 2^(64/4) = 2¹⁶ = 65.536` to match `0000*`.
- But, it's wrong `Πdiff(Σdiff) ≠ 2^(Σdiff/4)` for non round matches:
 - `Πdiff(15) = 2^(15/4) = 13,45 ≠ 15` to match `[0-1]****`.
 - `Πdiff(15) = 2^(70/4) = 185.363,8 ≠ 393.216` to match `0000[0-5]`.

#### Conclusion
We can conclude both formulas are equal for round matches, like `0****`.
But, both formulas are not equal for non round matches, like `0000[0-5]`.

**Comment by c-geek** [comment]
OK it's true, the transformation is not correct.

But why? First, if we observe the 2 functions Σ and Π we can see that they do not behave at all the same way:

| Match | Σ Difficulty | Π Difficulty 
| :--: | :--: | :--: 
| `*****` = `[0-9A-F]****` | 1 | 16^0 × (16 - 16 + 1) = 1
| `0****` | **16** | 16^0 × (16 - 1 + 1) = **16**
| `0[0-9A-F]***` | **17** | 16^1 × (16 - 16 + 1) = **16**

So it is probably not possible to even find a transformation, given their is no symmetry between the 2 functions. These 2 functions just do not mesure the same thing.

But here is the Σ Difficulty function I actually wrote in the protocol & code. It give symmetrical results with you proposal:

| Match | Σ Difficulty | Π Difficulty 
| :--: | :--: | :--: 
| `*****` = `[0-9A-F]****` | 0 | 16^0 × (16 - 16 + 1) = 1
| `[0-1]****` | 14 | 16^0 × (16 - 2 + 1) = **15**
| `0****` | **16** | 16^0 × (16 - 1 + 1) = **16**
| `0[0-9A-F]***` | **16** | 16^1 × (16 - 16 + 1) = **16**
| `0[0-9A-E]***` | 17 | 16^1 × (16 - 15 + 1) = 32
| `00***` | **32** | 16^2 × (16 - 16 + 1) = **256**
| `00[0-9A-F]**` | **32** | 16^2 × (16 - 16 + 1) = **256**

So I decided to trace these 2 curves on a [Calc Sheet](https://framadrop.org/r/XlMTop17Jl#VR3VXxXV/k/ufaP6S85ODwONhy1eFYDQWV0HjYNf9LU=):

![image](https://cloud.githubusercontent.com/assets/969136/18138382/ada32792-6fac-11e6-8def-2b9de1d75fb3.png)

As you can see, it is way easier to make any work using the Σ Difficulty *written in Duniter* than something else, because the function is just linear.

So the function is already perfect and there is nothing to change.

**Comment by M5oul** [comment]
May be I am still wrong, but I want to understand.
May be I am missing something.

But, I found that particular that common PoW difficulty changed two steps (78 - 80) many times around 80 which is limit between four and five zeros:
![pow_one_more_zero_or_less](https://cloud.githubusercontent.com/assets/4758871/20270523/b11897a2-aa87-11e6-96d4-1cf57e1210ac.png)

May be the difficulty modification is too high when using 5 zeros, then it goes back to 4 zeros.

May be I am wrong as it seems difficulty could have changed one time on those long plateau.

Π difficulty doesn't change between 78 and 80:

```bash
Minimal Proof-of-Work: 78 to match `0000[0-1]*`
### Difficulty to generate next block n°55053 for 13/13 nodes:
|    uid    |  Π diffi   |   Σ diffi |    match    |
|-----------+------------+-----------+-------------|
|  Jean-F   | 9.2 × 10^5 |        78 | 0000[0-1]*  |
|   mmpio   | 9.2 × 10^5 |        78 | 0000[0-1]*  |
|   cgeek   | 9.2 × 10^5 |        78 | 0000[0-1]*  |
|   moul    | 9.2 × 10^5 |        78 | 0000[0-1]*  |
|  modulix  | 9.2 × 10^5 |        78 | 0000[0-1]*  |
|   ktorn   | 9.2 × 10^5 |        78 | 0000[0-1]*  |
|  gege53   | 9.8 × 10^5 |        79 | 0000[0-0]*  |
| vincentux | 1.0 × 10^6 |        80 |   00000*    |
|   inso    | 1.0 × 10^6 |        80 |   00000*    |
|  gnu-tux  | 1.0 × 10^6 |        81 | 00000[0-E]* |
|   nay4    | 3.1 × 10^6 |        83 | 00000[0-C]* |
| kimamila  | 4.2 × 10^6 |        84 | 00000[0-B]* |
| pafzedog  | 4.2 × 10^6 |        84 | 00000[0-B]* |
```

**Comment by c-geek** [comment]
Yes, difficulty 79 is a bug, it has no sense. It should be either 78 or 80. The common difficulty `PowMin` never valuates at 79. That's OK.

But `/blockchain/difficulties` returns 79, and that's not normal. I have a post-it on my desktop saying "hey have a look at this bug", but I've not traced it on GitHub yet.

**Comment by c-geek** [comment]
By the way, this is surprising result:

```bash
Minimal Proof-of-Work: 78 to match `0000[0-1]*`
### Difficulty to generate next block n°55053 for 13/13 nodes:
|    uid    |  Π diffi   |   Σ diffi |    match    |
|-----------+------------+-----------+-------------|
|   inso    | 1.0 × 10^6 |        80 |   00000*    |
|  gnu-tux  | 1.0 × 10^6 |        81 | 00000[0-E]* |
```

Why is `Π diffi` identical whereas `match` isn't?

**Comment by M5oul** [comment]
> Why is `Π diffi` identical whereas `match` isn't?

Yep, it must be a bug on silkaj PoW computation side.
