### ISSUE TITLE
Blocks are not shared to all nodes sharing same pubkey

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#608]
Blocks are not shared to all nodes sharing same pubkey.
I could see that only one of my node receive new block.
There other node was still computing a block which was already shared by all the network.
At least one node (duniter.org:8999) knew the existence of the node which didn't receive the new block.
The node which didn't received the node is well accessible from Internet even with IP6.

**Comment by M5oul** [comment]
It happen one time. I can't reproduce it for now.

**Comment by c-geek** [comment]
Yes that's weird, because [this line takes care to forward systematically all documents to all the other endpoints of the node](https://github.com/duniter/duniter/blob/3ad93e33558f3d817ce40b882bbeb28fdea78ca9/app/lib/streams/router.js#L96-L100).

Also I just verified it here (the other endpoint here is prefixed by `M0_`):

```
2016-10-03T17:27:34+02:00 - debug: --> new Peer to be sent to 8 peer(s)
2016-10-03T17:27:34+02:00 - debug:  `--> to peer 8Fi1VSTbjk [member] (testnet.duniter.inso.ovh:80)
2016-10-03T17:27:34+02:00 - debug:  `--> to peer DeCipRbinE [member] (212.47.227.101:8999)
2016-10-03T17:27:34+02:00 - debug:  `--> to peer BR5DDeKff8 [member] (107.170.192.122:8999)
2016-10-03T17:27:34+02:00 - debug:  `--> to peer BmDsozDoF3 [member] (87.91.122.123:9330)
2016-10-03T17:27:34+02:00 - debug:  `--> to peer BSmbyQCeRx [------] (51.255.197.83:8999)
2016-10-03T17:27:34+02:00 - debug:  `--> to peer 2gFpaCHY4y [------] (163.172.130.151:8999)
2016-10-03T17:27:34+02:00 - debug:  `--> to peer TENGx7WtzF [------] (88.174.120.187:16120)
2016-10-03T17:27:34+02:00 - debug:  `--> to peer M0_HnFcSms [------] (88.174.120.187:9330)
```

I close it, feel free to reopen it if you encounter this problem again.

**Comment by M5oul** [comment]
It happen not a long time after starting the node.
That's a bit normal the node is not already known.

**Comment by c-geek** [comment]
OK then I see the issue: because previously to 0.31, [the freqency of the peer document was too high](https://github.com/duniter/duniter/commit/d4eb24564f9fd78472e3d7b0b4167d607a45f3f0), leading have peer documents with the very lastly known current block.

So when a 2nd node was started, there was no available blockstamp to write the new endpoint into the peer document.

I had this issue a lot when testing the shared pubkey functionality. Now this particular case should be fixed, so when you start a 2nd node the sharing is well done.

*But*, there might still exist a problem with the frenquency ... because I've set it to every 2 blocs (which is enough), but when you have 2 nodes, each node consumes a new blockstamp every 2 blocks ... so globally, we consume 1 blockstamp/node. If you have 2 nodes, or restart, change network configuration of one or several nodes several times, you consume a blockstamp each time, until there is no blockstamp left.

So I should fix that 😄

**Comment by c-geek** [comment]
To summarize, all the nodes sharing the same keyring also share the same blockstamp stock, which is incremented at every new block, and decremented at every new peer document issued.

They should all take care of this stock as a common resource.

**Comment by c-geek** [comment]
I've created #634 for that purpose.
