### ISSUE TITLE
Identity hash not found

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#610]
I frequently have this error message:
```bash
warn: Identity with hash '6ECB4D52E721361C31D839A5499B651AC99C644993B2F1705AF37296E0BFD8B7' not found
```

I can't found this pubkey on `/wot/lookup`.

It that a bug?

**Comment by c-geek** [comment]
Could you go in the UI > Settings > Backup and create a backup of your data and upload it somewhere? So I can debug this.

**Comment by M5oul** [comment]
It only happen during block generation.
Here is the [backup file](https://moul.re/jirafeau/f.php?h=36QfaF1z&d=1).

**Comment by c-geek** [comment]
So, this is not a bug: this error occurs when generating a block because we received an `IN` membership on our node, for a given identity, [but we don't actually find the corresponding identity](https://github.com/duniter/duniter/blob/be7e58d35b56a39f6651355dc210cd9543f3aaf0/app/lib/computation/blockGenerator.js#L264) in the sandbox.

This message will disappear when the membership is expired because of non-writing in the blockchain early enough.
