### ISSUE TITLE
Transaction present multiple times

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#728]
Take the result of this query : 

http://cgeek.fr:9330/tx/history/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

The TX with the hash `F8820AAD1F0963ECB0E938C2DBF03EF9A72DDFC68F156938C32B2A3D3DA4FAD6` is present multiple times.

**Comment by c-geek** [comment]
Indeed, it is because you are both in the issuers and receivers (one of the outputs requires your signature for futur unlock).

I could remove this transaction from `received` field since obviously you are more an issuer for this transaction than a receiver (your pubkey is explicitely in the `issuers` field).

Would it be OK on your side @blavenie? Any regression on Cesium if I make such a modification?

**Comment by blavenie** [comment]
Yes, could be great to simplify Cesium code.

**Comment by c-geek** [comment]
OK, so I will make this modification.
