### ISSUE TITLE
A wallet key is receiving dividends in ud/history

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#808]
See my wallet to test the destruction of money : 

http://gtest.duniter.org:10900/ud/history/EHRCKQn8Tua39rRkMtvaj5tpFGcg7yeKyr8S9fJnVKwE

**Comment by c-geek** [comment]
I get this result:

```json
{
  "currency": "gtest",
  "pubkey": "EHRCKQn8Tua39rRkMtvaj5tpFGcg7yeKyr8S9fJnVKwE",
  "history": {
    "history": []
  }
}
```

Which is correct, as this key is not member. What is the problem?

**Comment by Insoleet** [comment]
I was not seeing this last night. I should have grabbed the data.

Notice that it seems to be the cause of dividends appearing on tables of wallet keys. If you see this, you can checkout the url.

**Comment by Insoleet** [comment]
Reproduced : 

![image](https://cloud.githubusercontent.com/assets/1170293/22363195/d1815fea-e468-11e6-9874-dd81479f079c.png)

**Comment by c-geek** [comment]
OK I've also reproduced it:

http://cgeek.fr:10900/ud/history/6LfWH5bw7UvBSkPLasLeusKGRQTomtoM69LRfF2ZaHgH

```json

{
  "currency": "gtest",
  "pubkey": "6LfWH5bw7UvBSkPLasLeusKGRQTomtoM69LRfF2ZaHgH",
  "history": {
    "history": [
      {
        "block_number": 1,
        "consumed": true,
        "time": 1485510585,
        "amount": 74,
        "base": 0
      }
    ]
  }
}
```

This problem occurs on accounts with `balance < 1,00 Ğ`: the record we see in `/ud/history` is a consumption record (we can see `consumed: true`), aka money destruction. But because of a bug, it appears under `/ud/history`.

I will fix this.
