### ISSUE TITLE
Allow to post membership+certifications in one request

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#912]
From chat room : 
```
@Galuel: cgeek: il faut envoyer 6 documents signés séparés ? Bon, et ça se comporte comment à ce moment là ?
@cgeek: Ğaluel: oui séparément, ça se comporte comme dit plus haut : l'identité est soumise à l'état de la piscine du nœud auquel elle est envoyée. Il est possible de l'envoyer « toute seule » ou accompagnée d'une certification. Si la piscine contient dans sa liste des identités sans certifications, alors envoyer la sienne sans certification verra l'identité rejetée, alors qu'accompagnée elle passerait. Mais si dans cette piscine toutes les identités ont au moins une certif, il n'y a pas moyen de passer.
@Galuel: Donc c'est soit 1 certif et ça peut passer, mais 4 certifs de plus ne changent rien.
@cgeek: Oui
@cgeek: Sauf à effectivement développer un moyen d'envoyer « la paquet entier »
```

**Comment by c-geek** [comment]
Will be fixed by #927 + #885. Explanations.

### #927

With this correction, we won't have any global certification sandbox limit anymore. It will be per member, so any legit certification will just be written in the sandbox, and of course the certified identity will be written as well.

So the identity + certification won't suffer from sandboxes rejection anymore.

Also, the memberships sandbox has a lot of room: you always add a new membership, since a newer membership has a higher priority than an old one.

> What about new identities which has not been signed by anybody?

These identities can be created on nodes with room in their identity sandbox, or just export the identity by any way (e-mail, USB key, ...) and import this identity to certify it. Then, the certification propagation will create the identity on all the network's sandboxes.

### #885 

Also, a pulling mechanism will be added to retrieve ALL the registration package at once, through the /wot/requirements-of-pending/ URL. Slowly, the full package will be replicated on each node of the network.

I don't really want to implement an URL where we could post the whole package, because we already have enough tools to post the legitimate data (identity + certs + membership) once #927 will be implemented.
